# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all the tests"
  lane :test do
    begin
      run_tests(
        project: "LocationServices.xcodeproj",
        device: "iPhone 14",
        scheme: "LocationServices",
        result_bundle: true,
        output_directory: Dir.pwd + "/test_output"
      )
    ensure
      xcresult_path = Actions.lane_context[SharedValues::SCAN_GENERATED_XCRESULT_PATH]
      sh("echo xcresult_path=" + xcresult_path + " >> $GITHUB_ENV")
    end
  end

  desc "Build and upload to Testflight"
  lane :build_distribute do |options|
    increment_build_number(
      xcodeproj: "LocationServices.xcodeproj",
      build_number: options[:build_number]
    )
    setup_ci if ENV['CI']
    app_store_connect_api_key(
      key_id: options[:key_id],
      issuer_id: options[:issuer_id],
      key_content: options[:key_content],
      is_key_content_base64: true
    )
    match(type: "appstore")
    build_app(
      scheme: "LocationServices",
    )
    upload_to_app_store(
        skip_metadata: true,
        skip_screenshots: true,
        precheck_include_in_app_purchases: false
    )
  end
end
